# Generated by Django 6.0 on 2025-12-08 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Years',
            },
        ),
        migrations.CreateModel(
            name='AdminHOD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=100)),
                ('level_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AcuVerifyapp.educationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='AcuVerifyapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to='AcuVerifyapp.staff')),
            ],
            options={
                'verbose_name_plural': 'Guardians',
            },
        ),
        migrations.CreateModel(
            name='FeedbackStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_message', models.TextField()),
                ('feedback_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='AcuVerifyapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stream_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='AcuVerifyapp.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='AcuVerifyapp.classes')),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='AcuVerifyapp.streams')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='NotificationStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='AcuVerifyapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationGuardian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='AcuVerifyapp.guardian')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_notifications', to='AcuVerifyapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.DateField()),
                ('leave_message', models.TextField()),
                ('leave_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_reports', to='AcuVerifyapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_message', models.TextField()),
                ('feedback_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='AcuVerifyapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='AcuVerifyapp.classes')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='subject_specialization',
            field=models.ManyToManyField(blank=True, related_name='specialist_staff', to='AcuVerifyapp.subject'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='AcuVerifyapp.subject')),
            ],
            options={
                'unique_together': {('subject_id', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='AcuVerifyapp.academicyear')),
            ],
            options={
                'unique_together': {('term_name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('CAT', 'Continuous Assessment Test (CAT)'), ('MID_TERM', 'Mid-Term Exam'), ('END_TERM', 'End of Term Exam'), ('ASSIGNMENT', 'Assignment'), ('PROJECT', 'Project'), ('PRACTICAL', 'Practical'), ('QUIZ', 'Quiz'), ('OTHER', 'Other')], max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to='AcuVerifyapp.staff')),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='AcuVerifyapp.streams')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='AcuVerifyapp.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='AcuVerifyapp.term')),
            ],
            options={
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('HOLIDAY_ASSIGNMENT', 'Holiday Assignment'), ('PROJECT', 'Project'), ('REVISION', 'Revision Work'), ('OTHER', 'Other')], default='HOMEWORK', max_length=20)),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to='AcuVerifyapp.staff')),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='AcuVerifyapp.streams')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='AcuVerifyapp.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='AcuVerifyapp.term')),
            ],
            options={
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='AcuVerifyapp.academicyear')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='AcuVerifyapp.classes')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='AcuVerifyapp.staff')),
                ('stream_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_teachers', to='AcuVerifyapp.streams')),
            ],
            options={
                'unique_together': {('stream_id', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Guardian'), ('GRANDMOTHER', 'Grandmother'), ('GRANDFATHER', 'Grandfather'), ('UNCLE', 'Uncle'), ('AUNT', 'Aunt'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='AcuVerifyapp.guardian')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to='AcuVerifyapp.students')),
            ],
            options={
                'verbose_name_plural': 'Student Guardian Relationships',
                'unique_together': {('student_id', 'guardian_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentExamMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='AcuVerifyapp.exam')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_uploaded', to='AcuVerifyapp.staff')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='AcuVerifyapp.students')),
            ],
            options={
                'verbose_name_plural': 'Student Exam Marks',
                'unique_together': {('student_id', 'exam_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssignmentSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('LATE', 'Submitted Late'), ('GRADED', 'Graded')], default='NOT_STARTED', max_length=20)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('submission_text', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='AcuVerifyapp.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to='AcuVerifyapp.staff')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='AcuVerifyapp.students')),
            ],
            options={
                'verbose_name_plural': 'Student Assignment Submissions',
                'ordering': ['-submission_date', '-created_at'],
                'unique_together': {('assignment_id', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='AcuVerifyapp.attendance')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='AcuVerifyapp.students')),
            ],
            options={
                'unique_together': {('student_id', 'attendance_id')},
            },
        ),
        migrations.CreateModel(
            name='StaffSubjectStream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_subject_streams', to='AcuVerifyapp.academicyear')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='AcuVerifyapp.staff')),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='AcuVerifyapp.streams')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='AcuVerifyapp.subject')),
            ],
            options={
                'verbose_name_plural': 'Staff Subject Stream Assignments',
                'unique_together': {('staff_id', 'subject_id', 'stream_id', 'academic_year')},
            },
        ),
    ]
