# Generated by Django 6.0 on 2025-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
