# Generated by Django 6.0 on 2025-12-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0002_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
