# Generated by Django 6.0 on 2025-12-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0003_students_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streams',
            unique_together={('class_id', 'stream_name')},
        ),
    ]
