# Generated by Django 5.2.8 on 2025-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0005_alter_educationlevel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classteacher',
            old_name='class_id',
            new_name='stre_id',
        ),
        migrations.AlterField(
            model_name='students',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
