# Generated by Django 5.2.8 on 2025-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0006_rename_class_id_classteacher_stre_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='AcuVerifyapp.classes'),
        ),
    ]
