# Generated by Django 5.2.8 on 2026-01-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0009_documentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='AcuVerifyapp.assignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='document',
            field=models.FileField(upload_to='assignments/uploads/'),
        ),
    ]
