# Generated by Django 5.2.8 on 2026-01-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0010_documentupload_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('CLASS_ACTIVITY', 'Class Activity'), ('HOMEWORK', 'Homework'), ('GROUP_WORK', 'Group Work'), ('PROJECT', 'Project'), ('QUIZ', 'Quiz'), ('REVISION', 'Revision Work'), ('OTHER', 'Other')], default='ASSIGNMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('HOMEWORK', 'Homework'), ('GROUPWORK', 'Group Work'), ('HOLIDAY_ASSIGNMENT', 'Holiday Assignment'), ('PROJECT', 'Project'), ('REVISION', 'Revision Work'), ('CLASS_ACTIVITY', 'Class Activity'), ('QUIZ', 'Quiz'), ('OTHER', 'Other')], default='HOMEWORK', max_length=20),
        ),
    ]
