# Generated by Django 5.2.8 on 2026-01-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0011_documentupload_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='AcuVerifyapp.assignment'),
        ),
    ]
