# Generated by Django 5.2.8 on 2026-01-22 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0012_alter_documentupload_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('HOMEWORK', 'Homework'), ('HOLIDAY_ASSIGNMENT', 'Holiday Assignment'), ('PROJECT', 'Project'), ('REVISION', 'Revision Work'), ('OTHER', 'Other')], default='HOMEWORK', max_length=20),
        ),
        migrations.CreateModel(
            name='MyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AcuVerifyapp.staff')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentUpload',
        ),
    ]
