# Generated by Django 5.2.8 on 2026-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0013_alter_assignment_assignment_type_myupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myupload',
            name='file',
            field=models.FileField(upload_to='myuploaded/'),
        ),
    ]
