# Generated by Django 5.2.8 on 2026-01-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0014_alter_myupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myupload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
