# Generated by Django 5.2.8 on 2026-01-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0015_myupload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='myupload',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
