# Generated by Django 5.2.8 on 2026-01-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0016_myupload_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myupload',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('DOC', 'Word Document'), ('IMG', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='myupload',
            name='stream_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='AcuVerifyapp.streams'),
        ),
        migrations.AddField(
            model_name='myupload',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='AcuVerifyapp.subject'),
        ),
    ]
