# Generated by Django 5.2.8 on 2026-01-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcuVerifyapp', '0017_myupload_file_type_myupload_stream_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myupload',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='myupload',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='myupload',
            name='stream_id',
        ),
        migrations.RemoveField(
            model_name='myupload',
            name='subject_id',
        ),
    ]
